import Head from "next/head";
import Navbar from "~/components/navbar";
import Footer from "~/components/footer";
import AboutContent from "~/components/aboutcontent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rating Platform</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full h-full border-x border-slate-400 md:max-w-2xl bg-gray-500 rounded-md bg-clip-padding backdrop-filter backdrop-blur-lg bg-opacity-40 border border-gray-100">
          <Navbar/>
          <AboutContent/>
          <Footer/>
      </div>
      </main>
    </>
  );
}
