import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Navbar from "~/components/navbar";
import Landing from "~/components/landing";
import Footer from "~/components/footer";
import { toast } from "react-toastify";
import { ChangeEvent, FormEvent, useState } from "react";

export default function AddSkill() {
    const createSkill = api.skill.create.useMutation({
        onSuccess: () => {
            toast.success("We'll Review that!!");
        },
    });
    const [skill, setSkill] = useState<string>('');
    const handleAddSkill = () => {
        if(skill==='' || skill===null) {
            toast.warn("Can't have that");
            return;
        }
        createSkill.mutate({name:skill});
    };

    return(
        <>
        <Head>
            <title>SkillShow</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <main className="flex justify-center h-screen">
        <div className="w-full h-full border-x border-slate-400 md:max-w-2xl bg-gray-500 rounded-md bg-clip-padding backdrop-filter backdrop-blur-lg bg-opacity-40 border border-gray-100">

          <form onSubmit={handleAddSkill}>
            <input
                    className="p-2 m-2 text-black border-2 shadow-md rounded outline-none cursor-pointer"
                    value={skill}
                    onChange={(e:ChangeEvent<HTMLInputElement>)=>setSkill(e.target.value)}
                    >
            </input>
            <button className="shadow-md bg-orange-400 w-1/2 mx-auto rounded m-2 p-2">Send</button>
            </form>
        </div>
      </main>
      <Footer />
      </>
    );
}