import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { useUser } from "@clerk/nextjs";
import { SignInButton, SignOutButton } from "@clerk/nextjs";
import Navbar from "~/components/navbar";
import Landing from "../components/landing";
import Footer from "~/components/footer";
import Post from "./components/Post";
import CreatePost from "./components/CreatePost";

export default function Home() {
  const user = useUser();
  const {data} = api.posts.getAll.useQuery();
  console.log( data )


  return (
    <>
      <Head>
        <title>Rating Platform</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <Navbar />
        <Landing />
        <div className="w-full h-full border-x border-slate-400 md:max-w-2xl">
        <div className="border-b border-slate-400 p-4 flex">
          {!user.isSignedIn && 
            <div className="flex justify-center">
              <SignInButton/>
            </div>
          }
          {!!user.isSignedIn && <SignOutButton/>}
        </div>
        <div className="flex flex-col">
          {data?.map((post) => (
            <Post User={user} post={post}/>
            // <div key={post.id} className="p-8 border-b border-slate-400">{post.content}</div>
          ))} 
        </div>
        <CreatePost />
        </div>
        <Footer/>
      </main>
    </>
  );
}
