import Head from "next/head";
import Navbar from "~/components/navbar";
import Footer from "~/components/footer";
import Dashboard from "~/components/dashboard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
        <main className="flex justify-center h-full">
          <Dashboard/>
        </main>
      <Footer/>
    </>
  );
}
